### PR TITLE
Clocker configuration files

### PR DESCRIPTION
**Pull request by grkvlt**
Initial configuration for Clocker with Vagrant

### CODE REVIEW

**Comment by grkvlt** [comment]
More commits to follow for other recipe configuration

**Comment by andreaturli** [comment]
lgtm, tested on my machine, it works!

**Comment by how2dock** [comment]
Do we need to have the private and ssh keys in there. would be nicer to create them manually ? no ?

**Comment by grkvlt** [comment]
OK, probably good, I will do that for the AWS recipe, as well

**Pull request merged**
